FROM confluentinc/cp-kafka-connect:7.9.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-gcs:latest

# Download Debezium Connector
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:latest

# Set the plugin path if needed
# ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

